# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: queueme_development
  pool: 5
  username: jimmy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: queueme_test
  pool: 5
  username: jimmy
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: queueme_production
  pool: 5
  username: jimmy
  password:
